// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// callrnorm
Rcpp::NumericVector callrnorm(int n);
RcppExport SEXP UseZiggurat_callrnorm(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(callrnorm(n));
    return __result;
END_RCPP
}
// setZigguaratSeed
bool setZigguaratSeed(const int seed);
RcppExport SEXP UseZiggurat_setZigguaratSeed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    __result = Rcpp::wrap(setZigguaratSeed(seed));
    return __result;
END_RCPP
}
// callZiggurat
Rcpp::NumericVector callZiggurat(Rcpp::NumericVector X);
RcppExport SEXP UseZiggurat_callZiggurat(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    __result = Rcpp::wrap(callZiggurat(X));
    return __result;
END_RCPP
}
