// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// callrnorm
Rcpp::NumericVector callrnorm(int n);
RcppExport SEXP UseZiggurat_callrnorm(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(callrnorm(n));
    return __result;
END_RCPP
}
// setZigguratSeed
void setZigguratSeed(const int seed);
RcppExport SEXP UseZiggurat_setZigguratSeed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    setZigguratSeed(seed);
    return R_NilValue;
END_RCPP
}
// callZiggurat
Rcpp::NumericVector callZiggurat(int n);
RcppExport SEXP UseZiggurat_callZiggurat(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(callZiggurat(n));
    return __result;
END_RCPP
}
