# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callrnorm <- function(n) {
    .Call('UseZiggurat_callrnorm', PACKAGE = 'UseZiggurat', n)
}

setZigguaratSeed <- function(seed) {
    invisible(.Call('UseZiggurat_setZigguaratSeed', PACKAGE = 'UseZiggurat', seed))
}

callZiggurat <- function(n) {
    .Call('UseZiggurat_callZiggurat', PACKAGE = 'UseZiggurat', n)
}

